Sprint 16
H3ARTgg/Tracker pull request #3
Opened 2023-05-18 20:22 UTC by H3ARTgg

Хотелось бы узнать, правильно ли реализовал MVVM
И, если не сложно, послушать опытный выход из ситуации по поводу скроллИндикатора (в TrackersCell подробнее об этом)

2023-05-20 09:49 UTC, IBDesignable requested changes
Тут фидбек чисто про MVVM


Что хорошо:

- не нашла во ViewModel серьезных признаков UI-слоя) как и в Model)
- сделаны ViewModel-ы для внутренних вьюх, это прям круто

Что надо исправить:
- некоторые вьюхи "слишком умные", держат слой Model и не делятся им с вьюмоделью. Нужно выносить любую работу с данными и логику связанную с ней во ViewModel
- частая ошибка это способ сборки MVVM модуля. Почему-то вьюмодели инициализируются от модели прямо во вью-контроллерах. Буду признательна получить фидбек, почему придумалось так и чего не хватило чтобы сделать лучше)
- структура файлов: обычно это папка в которой лежат два и более файлов. ViewModel и View/ViewController, другие файлы - это модели, вспомагательные классы, фабрики. Папка называется по содержимому: TrackerCategory. TrackerCategoryCell. Сейчас в проекте модели живут отдельно от их вью-части, при росте модулей это будет не удобно в навигации

Эти две штуки надо править по рекомендациям, отдашь на ревью – после дам зеленый свет на обархитектуривание остальных экранов)

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Onboarding/OnboardingViewController.swift
> +
Можно лучше:
- Если заметить, то экраны то одинаковые, отличия лишь в параметрах: текст картинка. Верстаются одинаково. Можно было сделать один контроллер и конфигурировать его моделью.

Также, я не знаю почему во всех туториалах UIPageViewController все контроллеры создаюются вот таким вот образом, я не считаю это хорошей практикой: создали больше, чем может понадобится. Например, пользователь открыл приложение и сразу закрыл онбординг. А мы зачем-то все страницы загрузили.
Лучше все-таки создавать новые экраны в момент запроса системы - в методах датасорса. 
Но для этого нужно четко описать логику навигации. Я для этого я бы использовала Enum для описания видов страниц, и вычислимые свойства к нему (например изображение фона, текст онбординга), а также вычислимые к нему next/prev. От значения енама в таком случае будет удобно создавать экран онбординга. 

[реализация онбординга с енамом](https://github.com/cjlarsen/Tutorials/tree/master/PageControllerTutorial ) – пример не самый удачный по качеству кода, и не все идеи реализованы. Да и качество кода страдает, но идею понять можно.

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Onboarding/OnboardingViewController.swift
> +        NSLayoutConstraint.activate([
ничего не мешает делать это в одной группе

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Onboarding/SecondPageViewController.swift
> +    private var button = UIButton()
все элементы должны быть let

2023-05-20 09:49 UTC, IBDesignable commented on Tracker.xcodeproj/project.pbxproj
> +		1DB41F222A14213400FB0F97 /* Observable @pw.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = "Observable @pw.swift"; sourceTree = "<group>"; };
Заметила пробелы в названиях файлов – от них лучше избавиться.

А этот файл `Observable @pw.swift` можно и просто `Observable` назвать. Нет такого обычая про propertyWrapper в файлах указывать :) 

Я конечно могу ошибаться – но ни разу не видела)

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
> +    private var daysCount: Int = 0 {
id и daysCount  отвественность viewModel, нужно перенсти их в нее и если ячейке они нужны – добавить сетеры

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
>          didSet {
что-то страшное тут происходит 😀


Вообще didSet/willSet/Get/Set у вычисляемыъ свойств не принято делать такими жирными и объемными.

обычно функции делают какую-то работу,а свойства только заполняют/отдают значения, ну может быть еще какую-то работу запускают. 

Но описывать портянку ниже – это очень грязная практика.

Если смотреть тут за содержимым, то ты на установку свойства viewModel начинаешь настраивать и размещать вьюхи. А если два раза свойства установят, что произойдет? 

Это точно нужно разделить: вьюшки налепить на ячейку можно и без модели. а вот наполнение данными и байдинг изменений, уже можно делать на установку вью модели.

Но лучше не через прямой доступ к свойству. Его следует заприватить, и явно прописать метод setup(viewModel)

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
> +    private var daysCount: Int = 0 {
Это придется доработать, чтобы сдать работу

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
>          didSet {
Это придется доработать, чтобы сдать работу

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
> +            viewModel.isRecordExists ? setDone() : setNotDone()
В данном случае тернарник короткий, поэтому не критично. но подсвечу, что лучше все-таки тернарный оператор использовать для возвращаемых значений. 

Например, получить какое-то значение:`let status = isRecorfExist ? .doneStatus : .notDoneStatus`, и установить его в каком-нибудь методе.

А если моделировать такой статус (как в абстрактном примере выше, то наверное его стоит получать сразу из вьюмодели).

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
> +                daysButton.isUserInteractionEnabled = false
daysButton.isUserInteractionEnable = !viewModel.currentDate.isBiggerThanRealTime()

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
>              delegate?.didRecieveNewRecord(false, for: id)
Это логика (есть ветвление, работа с данными модели), ее нужно запрятать во ViewModel

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell.swift
> +         */
CollectionView - это наследний UIScrollView, ты можешь попробовать задать отступы свойством [contentInset](https://developer.apple.com/documentation/uikit/uiscrollview/1619406-contentinset) 

![image](https://github.com/H3ARTgg/Tracker/assets/121577115/494b5ec4-406b-433d-9182-6e312e559f24)

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersViewController.swift
> +        viewModel = TrackersViewModel(date: currentDate)
Я проверила уже какое-то количество работ этого спринта, и возможно, это системная ошибка.
Подскажи, инициализировать вьюмодель внутри контроллера – так рассказывается в учебнике?

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersViewController.swift
> +        viewModel = TrackersViewModel(date: currentDate)
Смотри в чем тут проблема: View слой не должен знать ничего про Model, но в данном случае он ей владеет, то есть знает про `currentDate `. 

В архитектуре MVVM про Model знает только ViewModel, поэтому и инициализироваться она должна от модели отдельно от вью-контроллера.
ViewController/View принимают уже созданные ViewModel, чтобы исключить такую ошибку.

То есть должна получиться матрешка:
Создается Model (или получается из другого модуля), затем от нее создается ViewModel (вьюмодели могут держать сервисы, данные),  и затем от ViewModel - View(ViewController). 
Байдинги настраиваются после инициализации (например, если ты решаешь задачу делегатами) 

Делают это обычно с помощью фабричного паттерна, то есть пишут такой объект, который делает только одну задачу - создает экранный модуль, и возвращает UIViewController. Чистую закрытую, не конкретную реализацию. Такие фабрики называют ассамлеблями, они могут держать необходимый контекст и зависимости, чтобы собрать модуль.
Модуль может собираться функцией `assemble(аргументы если нужно передать с другого VC) -> UIViewController` в месте вызова экрана (то есть при навигации на него). 

Я приношу извинения, если этот блок недостаточно хорошо освещен в учебнике – я обязательно передам это коллегам. А пока все же настаиваю на фиксе этой штуки: достаточно только перенести создание всех связей в методы где происходит навигация, очень круто - если будет сделана фабрика описанная выше (TrackerCategoryAssembly)

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/TrackersViewController.swift
> +        return viewModel?.trackersCategories.count ?? 0
если вью модель будет получаться в инициализаторе, от опционала можно будет избавиться

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersCellViewModel.swift
> +    let delegate: TrackersCellDelegate
тут стоит добавить слабую ссылку :) делегат ж

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersCellViewModel.swift
> +    let delegate: TrackersCellDelegate
weak свойства могут держать только ссылочные типы, придется поправить на класс

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +import UIKit
UIKIt-а во ViewModel/Model слоях не должно быть. Если что-то просочилось - надо пробовать обходиться без юайных моделей, делать более простые модели для общения

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +    private(set) var stringCategories: [String] = []
Мы не рассказываем про DI подробно, но это не поводод забывать, что зависимости лучше инджектировать, самый лучший способ без дополнительных библиотек - это иниты :)

созданные зависимости внутри, да еще и не закрытые протоколами делают код связным.

предлагаю переделать

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +    }
тут порядок перепутан: сначала пишем инит, затем публичные методы, затем приватные

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +        if let trackers = trackerStore.trackers {
метод получился с губокой вложенностью (4!), программисты стремятся писать плоский код (без ветвлений)

В данном случае, этот if можно заменить на guard, тем самым уменьшим вложенность на 1

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +                var number = 0
по названию не могу понять что это за число, нейминг бы поменять. 
Пока сложно понять как эту функцию еще на кусочки побить, лучше тебе про это самому подумать :) 

Попробуй разделить задачи. может будет проще тогда в плане вложенных циклов

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +                            .recordsCountFor(trackerID: tracker.id!)
за форс анврап - цап! неужели никак без этого нельзя обойтись?

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +import UIKit
Мне кажется здесь можно будет просто поменять на Foundation, но на всякий случай - перепроверь

2023-05-20 09:49 UTC, IBDesignable commented on Tracker/Trackers/ViewModels/TrackersViewModel.swift
> +    private let uiColorMarshalling = UIColorMarshalling()
неймнинг не очень удачный, так ты раскрываешь, что внутри какая-то работа с UIColor происходит. UI -приставку давай оставим UIKit-у. Свои классы называть иначе

2023-05-20 09:49 UTC, IBDesignable requested changes
Тут фидбек чисто про MVVM


Что хорошо:

- не нашла во ViewModel серьезных признаков UI-слоя) как и в Model)
- сделаны ViewModel-ы для внутренних вьюх, это прям круто

Что надо исправить:
- некоторые вьюхи "слишком умные", держат слой Model и не делятся им с вьюмоделью. Нужно выносить любую работу с данными и логику связанную с ней во ViewModel
- частая ошибка это способ сборки MVVM модуля. Почему-то вьюмодели инициализируются от модели прямо во вью-контроллерах. Буду признательна получить фидбек, почему придумалось так и чего не хватило чтобы сделать лучше)
- структура файлов: обычно это папка в которой лежат два и более файлов. ViewModel и View/ViewController, другие файлы - это модели, вспомагательные классы, фабрики. Папка называется по содержимому: TrackerCategory. TrackerCategoryCell. Сейчас в проекте модели живут отдельно от их вью-части, при росте модулей это будет не удобно в навигации

Эти две штуки надо править по рекомендациям, отдашь на ревью – после дам зеленый свет на обархитектуривание остальных экранов)

2023-05-20 09:53 UTC, IBDesignable commented
Не понравилось, что ячейки коллекций прямоугольные, хотя в дизайне скорее квадратные. 

<img width="511" alt="Снимок экрана 2023-05-20 в 11 48 58" src="https://github.com/H3ARTgg/Tracker/assets/121577115/ea4fa2e2-a27e-4399-8822-64e1b414a1af">

Еще обращу внимание на скругление у рамки, оно не совсем корректное. Почитай как происходят вычисления, чтобы было красиво https://twitter.com/gavmn/status/1545387084017532929 

Еще заметила неочевидное для меня поведение:
первый раз я создаю несколько категорий, затем выбираю одну, и только потом создаю первый трекер. При повторном возвращении на экран списка категорий - мои созданные категории стираются, остаются только те, что были использованы в трекере. Это не очень предсказуемое поведение для пользователей, хорошо бы его поправить: создавать все категории, которые были введены пользователем. И показывать все категории, даже если у них нет своих трекеров.

2023-05-20 10:02 UTC, IBDesignable commented on Tracker/Application/SceneDelegate.swift
> +        }
работа с `UserDefault` сделана прям плохо – в предыдущем модуле разбирали, показывали что нужно обернуть в класс, сделать ему специальные методы или хотя бы свойство) 

А тут прям на голую 🤣 поленился, Максим)

2023-05-23 09:30 UTC, H3ARTgg commented on Tracker/Onboarding/OnboardingViewController.swift
> +        NSLayoutConstraint.activate([
Согласен, но я так делаю для визуального удобства (по крайней мере так считаю, что это удобно).
Чтобы не в куче искать констрейнты в случае чего, а по группам типа. Вот это лайаут для кнопки, а ниже только для pageControl

2023-05-23 10:56 UTC, H3ARTgg commented on Tracker/Application/SceneDelegate.swift
> +        }
Подумал, раз всего одно взаимодействие с UserDefaults, то сделаю так..
Не подумал с точки зрения расширяемости и поддержки кода в будущем, извиняюсь

2023-05-23 13:03 UTC, H3ARTgg commented on Tracker/Onboarding/SecondPageViewController.swift
> +    private var button = UIButton()
Иногда я оставляю var button, потому что хочу задать как системную кнопку. А если делать это по типу:
let button: UIButton = {
    let button = UIButton.systemButton(with: .xMark, target: self, action: #selector(didTapButton))
    return button
}()

то при нажатии на кнопку он выкидывает с тем, что не найден target, поэтому делаю его var и переинициализирую как системную в функции, где у меня настраивается сама кнопка

2023-05-23 15:55 UTC, H3ARTgg commented
> некоторые вьюхи "слишком умные", держат слой Model и не делятся им с вьюмоделью. Нужно выносить любую работу с данными и логику связанную с ней во ViewModel
Поправил

> частая ошибка это способ сборки MVVM модуля. Почему-то вьюмодели инициализируются от модели прямо во вью-контроллерах. Буду признательна получить фидбек, почему придумалось так и чего не хватило чтобы сделать лучше)
Совсем вылетело из головы об этом, теперь ViewModel для TrackersViewController инициализируется в tabBar. 
А viewModel для Cell из самого TrackersViewModel. А придумалось так из-за примеров в самом Практикуме.

> структура файлов: обычно это папка в которой лежат два и более файлов. ViewModel и View/ViewController, другие файлы - это модели, вспомагательные классы, фабрики. Папка называется по содержимому: TrackerCategory. TrackerCategoryCell. Сейчас в проекте модели живут отдельно от их вью-части, при росте модулей это будет не удобно в навигации
Добавил папки в папке Trackers. Только по поводу моделей Tracker, TrackerCategory, TrackerRecord:
У меня они используются не только в классах с приставкой Tracker*, например, я передаю Tracker из HabitOrEventViewController. Как быть в таком случае? Все равно оставлять в папке Trackers?
А по поводу CoreData папки (где находятся Stores и датамодель), нужно ли её переносить тоже в Trackers (что сделал) или оставить как было?

2023-05-23 15:56 UTC, H3ARTgg commented
Постарался поправить по всем рекомендациям и ошибкам

2023-05-24 15:52 UTC, IBDesignable commented on Tracker/Onboarding/OnboardingViewController.swift
> +        NSLayoutConstraint.activate([
ну можно и так, не настаиваю, как альтернатива разделения констрейнтов (визуально), можно оставлять пробелы внутри массива)

2023-05-24 15:53 UTC, IBDesignable commented on Tracker/Onboarding/SecondPageViewController.swift
> +    private var button = UIButton()
попробуй добавить lazy - тогда выкидывать с таргетом не будет. Ну и ничего страшного, если настройку экшенов сделать отдельно от настройки вьюхи.

2023-05-24 15:55 UTC, IBDesignable commented on Tracker/Application/SceneDelegate.swift
> +        }
с опытом наладится) все окей 👌 ты молодец)

2023-05-24 16:04 UTC, IBDesignable commented
> Добавил папки в папке Trackers. Только по поводу моделей Tracker, TrackerCategory, TrackerRecord:
У меня они используются не только в классах с приставкой Tracker*, например, я передаю Tracker из HabitOrEventViewController. Как быть в таком случае? Все равно оставлять в папке Trackers?

Модели(структры, типы) которые используются в разных частях приложения обычно хранят не внутри папки с модулем. (папка Models у MovieQuiz)
Если больше нигде не используется, то можно оставить внутри папки с модулем. 

Тут важно разделять понятие модели в MVVM и модели для описания структуры данных. 
Вот модель данных:
```swift
enum OnboardingPage { case one, two }
```
и это тоже  модель

```swift 
struct TrackerRecord { let id: UUID }
```

Еще моделью называют любые зависимости у модуля (M)VVM: связь со стораджами, сторами, менеджерами, исходные данные в виде моделей данных. 
Этой модели не обязательно лежать в папке с модулем MVVM, она может состоять из кучи разных зависимостей из разных частей приложения.
В других архитектурой, этой же модель могут называть Entity (VIPER). 
Ориентируются обычно по контексту, но я решила расписать, чтобы не вводить в заблуждение.

> А по поводу CoreData папки (где находятся Stores и датамодель), нужно ли её переносить тоже в Trackers (что сделал) или оставить как было?

Оставить как было - лучше. Но и то что ты сделал не ошибка.
Здесь лучше ориентироваться на слои приложения. 
Data Layer > Service Layer > Presentation Layer 
Для каждого слоя можно завести отдельную папку: Stores, Managers/Services, UI.
А вот все экраны, и все их принадлежности ui-ного типа, можно прятать в UI папку, ровно также как и папку с MVVM модулем.

2023-05-24 16:45 UTC, IBDesignable approved these changes

2023-05-24 16:45 UTC, IBDesignable commented on Tracker/Helpers/Storage.swift
> +    }
1) рекомендую подумать а не стоило ли использовать Bool для этой задачи(UserDefaults поддерживает приметивы, не только объекты). код упростится
2) Статикой удобно пользоваться, когда у нас нет DI - поэтому не возражаю против синглтона, но функции здесь избыточно сделаны статически, можно упростить. Да, тут на этот класс тесты не придется писать, чтобы протоколом еще реализацию закрывать, но так ты не учишься писать в [протоколо-ориентированной парадигме](https://habr.com/ru/articles/473798/)

2023-05-24 16:45 UTC, IBDesignable commented on Tracker/Onboarding/OnboardingViewController.swift
> +           let currentIndex = pages.firstIndex(of: pageSample.page) {
круть!

2023-05-24 16:45 UTC, IBDesignable commented on Tracker/Onboarding/PageSample.swift
> +final class PageSample: UIViewController {
давай договоримся, что у всех контроллеров в нейминге будет оставаться ViewController. Иначе в проекте будет неудобно ориентироваться) 
Это такие устоявшиеся постулаты 😅 что даже аргументировать нечем)

2023-05-24 16:45 UTC, IBDesignable commented on Tracker/Onboarding/OnboardingViewController.swift
> +        guard let pageIndex = pages.firstIndex(of: pageSample.page) else {
если к Pages добавить расширение next/prev, то поиском можно будет пренебречь:
```swift
let nextPage = pageSample.page.next() 
PageSample(page: nextPage)
```

2023-05-24 16:45 UTC, IBDesignable commented on Tracker/Trackers/TrackersCell/TrackersCellViewModel.swift
> +         rowNumber: Int) {
Можно подробно так поля не расписывать, а использовать модель данных с этими полями) будет попроще вероятно)

2023-05-24 16:45 UTC, IBDesignable commented on Tracker/Trackers/TrackersView/TrackersViewModel.swift
> +    init(date: Date, trackerCategoryStore: TrackerCategoryStoreProtocol) {
Здесь вот как будто хорошо что передаешь стор trackerCategoryStore, 
но trackerRecordStore, weekDayStore - все создаются внутри вью-модели.

2023-05-24 16:48 UTC, IBDesignable commented
Вот тут у плюсика цвет не в макете
<img width="222" alt="Снимок экрана 2023-05-24 в 19 47 27" src="https://github.com/H3ARTgg/Tracker/assets/121577115/0e3e801d-f2d3-4a83-a83d-5c92d43d40dc">

2023-05-24 16:51 UTC, IBDesignable commented on Tracker/Trackers/TrackersView/TrackersViewModel.swift
> +    init(date: Date, trackerCategoryStore: TrackerCategoryStoreProtocol) {
Решила не возвращать тебе этот недочет на еще одну итерацию.

Тут все-таки нужно работать над другим архитектурным приемом - DI, что за рамками этого спринта)

2023-06-02 11:47 UTC, merged